### ISSUE TITLE
The style of the input file has a display: none

### ISSUE THREAD

**Issue by ahelord** [jgpacheco/ngx-s3-uploader#12]
The style of the input file has a display: none
![screen shot 2017-12-10 at 7 26 33 pm](https://user-images.githubusercontent.com/21299810/33811363-8386846a-dde0-11e7-9c59-48811a1525f9.png)

**Comment by jgpacheco** [comment]
What is the issue?

**Comment by ahelord** [comment]
@jgpacheco the input is not shown and therefore nothing is seen.

**Comment by jgpacheco** [comment]
@ahelord The input is hidden so that the directive can be used without necessarily showing an input field. In the following example, the directive is used as a wrapper for an icon, not input file is shown:

```
    <s3-uploader class="user-edit-btn" (success)="avatarUploaded($event)" (error)="avatarUploadError($event)">
      <i class="write icon"></i>
    </s3-uploader>
```

![image](https://user-images.githubusercontent.com/8032466/34749606-6287eb58-f570-11e7-9308-70e65345c12b.png)

**Comment by ahelord** [comment]
@jgpacheco perfecto thanks.
